model:
    # 可将scheduler和sampler放入config
    # type:

diffwave:
    embed_dim: 256
    residual_layers: 24
    residual_channels: 32
    dilation_cycle_length: 8

net:
    in_chn: 3
    num_tokens: 32
    depth: 24
    # default parameters
    dropout: 0
    embedding_dim: 128
    transpose: True

s4:
    mode: 'nplr'
    measure: 'legs'
    bidirectional: True
    # d_state: 64
    transpose: True


train:
    lr: 0.0001
    batch_size: 50
    epoch: 88
    save_path: 'checkpoints'    # relative path


sample:
    model_path: 'checkpoints'
    result_path: 'result/generate'
    # batch_size: 10  # 10 is good
    data_shape: !!python/tuple [64, 3, 512]


hijack:
    model_path: 'checkpoints'
    result_path: 'result/hijack'
    # batch_size: 10  # 10 is good
    data_shape: !!python/tuple [64, 3, 512]
    _lambda: 0.5 # as default

optim:
    batch_size: 9
    