data:
    dataset:

s4:
    mode: 'diag'
    measure: 'diag-lin'
    bidirectional: True
    d_state: 16
    
    transpose: True

net:
    in_chn: 1
    num_tokens: 1
    depth: 1
    # default parameters
    dropout: 0
    embedding_dim: 128
    transpose: True

model:
    type:

sampling:
    batch_size:
    
path:
    save_path: 'projects/_BSS_hijack/result'