# data:
#     dataset:

# s4:


# net:
    in_chn: 1
    num_tokens: 1
    depth: 1
    # default parameters
    dropout: 0
    embedding_dim: 128
    transpose: True

# model:
#     type:

# sampling:
#     batch_size:
    